### ISSUE TITLE
Style Attribute

### ISSUE THREAD

**Issue by brock-noah** [farism/stylegator#125]
Adding `style` without a JSX attr obj to a tag or component breaks the page.
```
Error: The `style` prop expects a mapping from style properties to values, not a string.
```

Ways to reproduce:
- write `style` on an element
- paste `style=''` on an element
- remove the style obj and JSX attr obj from an element already with an inline style. (like avatar css)

Ways to get around:
- type `style={}` without hesitation
- write a different attr, then change it. `test={}` => `style={}`

**Comment by farism** [comment]
Thanks, we noticed this the other day actually. I was going to investigate the new React16 error boundaries to see if that may help. Will keep you updated.

**Comment by farism** [comment]
https://github.com/farism/stylegator/pull/129
